# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 4 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Haawron # jekyll-seo-tag > Owners twitter username
author: Hyeogeon Lee # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Hyeogeon Lee # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Haawron
    - https://www.facebook.com/hyogun.lee.3
    #- https://www.linkedin.com/in/daviddarnes
    - https://plus.google.com/116348548565230043793
    - https://github.com/Haawron

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Seoul # Timezone for blog posts and alike

# 5. Collections, Blog 대문
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "The repository of my studies" # The post list page content
    feature_text: |
      <h1 style="color:white;font-weight:bold;font-style:normal;font-size:60px">
      Blog
      </h1>
    feature_image: "https://i.imgur.com/p5uVBPx.png"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing // 카톡이나 이런 곳 공유할 때 나오는 사진

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: ko-KR  #en-GB # Set the site language  이상 생기면 롤백 ㄱㄱ
title: "하우론 딥러닝" # Site name or title, also used in jekyll-seo-tag, 맨 위의 탭에 나올 이름
logo: "/assets/wing_logo.svg" # Site logo, also used in jekyll-seo-tag
description: "The personal deep learning lab by Haawron" # Site description and default description, also used in jekyll-seo-tag
url: "https://haawron.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/Haawron/Haawron.github.io"
email: "gunsbrother@naver.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://i.imgur.com/B2Sq1xF.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  Categories: /categories/
#  Search: /search/  # 이건 나중에 페이지 커지면 달자
#  Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by David Darnes: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Facebook: https://www.facebook.com/hyogun.lee.3
  Twitter: https://twitter.com/Haawron
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/116348548565230043793
  GitHub: https://github.com/Haawron
  link: https://github.com/Haawron
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  Facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
